[build]
builder = "nixpacks"
buildCommand = "cd back-end && npm install"

[deploy]
startCommand = "cd back-end && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3